name: CI
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [questdb, kafka, nautilus]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build ${{ matrix.service }}
        run: docker compose build ${{ matrix.service }}
      - name: Smoke tests
        if: matrix.service == 'nautilus'
        run: docker compose run --rm nautilus pytest -q
